skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
airdrop_claim = "2NepmY26ip3y5gPWaY5ZoAUUWNtqqMjDobiAyFtCj5Jf"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
